/** Declaration file generated by dts-gen */

export class Board {
    constructor(...args: any[]);

    compress(...args: any[]): void;

    extract(...args: any[]): void;

    toMultiArray(...args: any[]): void;

    toString(...args: any[]): void;

    toStringFull(...args: any[]): void;

}

export class CountDown {
    constructor(...args: any[]);

    toString(...args: any[]): void;

}

export class Graveyard {
    constructor(...args: any[]);

    toString(...args: any[]): void;

}

export class KPGN {
    constructor(...args: any[]);

    toJson(...args: any[]): void;

}

export class KhmerChess {
    constructor(...args: any[]);

    addUpdateRenderEventListener(...args: any[]): void;

    ascii(...args: any[]): void;

    board(...args: any[]): Piece[][];

    clear(...args: any[]): void;

    gameOver(...args: any[]): void;

    get(...args: any[]): void;

    graveyard(...args: any[]): Piece[];

    history(...args: any[]): void;

    inCheck(...args: any[]): void;

    inCheckmate(...args: any[]): void;

    inDraw(...args: any[]): void;

    inDrawCount(...args: any[]): void;

    inStalemate(...args: any[]): void;

    kpgn(...args: any[]): void;

    load(...args: any[]): void;

    loadKpgn(...args: any[]): void;

    move(move: Move): boolean;

    moves(...args: any[]): void;

    put(...args: any[]): void;

    remove(...args: any[]): void;

    removeUpdateRenderEventListener(...args: any[]): void;

    ren(...args: any[]): void;

    reset(...args: any[]): void;

    turn(...args: any[]): void;

    undo(...args: any[]): void;

    validateRen(...args: any[]): void;

    static title: string;
    static version: string;

}

export class KqMoved {
    constructor(...args: any[]);

    toString(...args: any[]): void;

}

export class Move {
    from: string;
    to: string;
    jump: boolean;
    capture: string
    constructor(from: string, to: string, jump?: boolean, capture?: string);
    toJson(): {
        from: string;
        to: string;
        jump: string;
        capture: string;
    };
}

export class Piece {
    type: string;
    color: string;
    constructor(...args: any[]);

    toOrigin(...args: any[]): void;

    toString(...args: any[]): void;

}

export class Player {
    constructor(...args: any[]);

    toJson(...args: any[]): void;

}

export class Pos {
    constructor(...args: any[]);

    toPString(...args: any[]): void;

    toString(...args: any[]): void;

}

export class REN {
    constructor(...args: any[]);

    isInvalidPieceCount(...args: any[]): void;

    toString(...args: any[]): void;

}

export class Result {
    constructor(...args: any[]);

    toJson(...args: any[]): void;

}

export class Timer {
    constructor(...args: any[]);

    toJson(...args: any[]): void;

}

export const DEFAULT_BOARD_STR: string;

export namespace boardHelper {
    const BOARD_SEPARATOR: string;

    const EMPTY_PIECE: string;

    const HORIZONTAL_CODE_LETTERS: string;

    const HORIZONTAL_NOTE_LETTERS: string[];

    const HORIZONTAL_NOTE_LETTERS_ASCII: string;

    const PIECE_COLOR_BLACK: string;

    const PIECE_COLOR_WHITE: string;

    const PIECE_TYPE_BORK: string;

    const PIECE_TYPE_KOL: string;

    const PIECE_TYPE_NEANG: string;

    const PIECE_TYPE_SDECH: string;

    const PIECE_TYPE_SES: string;

    const PIECE_TYPE_TOUK: string;

    const PIECE_TYPE_TREY: string;

    const ROW_FIRST_INDEX: number;

    const ROW_LAST_INDEX: number;

    const ROW_NUMBER: number;

    const VERTICAL_NOTE_LETTERS: string[];

    const VERTICAL_NOTE_LETTERS_ASCII: string[];

    const mask: any;

    const pieceHash: {
        a: string;
        b: string;
        c: string;
        d: string;
        e: string;
        f: string;
        g: string;
        h: string;
        i: string;
        j: string;
        k: string;
        l: string;
        m: string;
        n: string;
    };

    function checkCount(...args: any[]): void;

    function checkCountable(...args: any[]): void;

    function codeP(h: any, v: any): void;

    function convertMask(...args: any[]): void;

    function extractPiecesToArray(...args: any[]): void;

    function filterPieceInBoard(...args: any[]): void;

    function generatePosesCanMove(...args: any[]): void;

    function getCharPieceFromString(...args: any[]): void;

    function getCharPieceInPos(...args: any[]): void;

    function getColorArray(...args: any[]): string[];

    function getHashKey(...args: any[]): void;

    function getKingInDanger(...args: any[]): void;

    function getKingWillInDanger(...args: any[]): void;

    function getPieceCanMovePoses(...args: any[]): void;

    function getPieceCanMovePosesValid(...args: any[]): void;

    function getPieceCharArray(...args: any[]): string[];

    function getPieceCode(...args: any[]): void;

    function getPieceInPos(...args: any[]): void;

    function getPieceKeyByName(...args: any[]): void;

    function getPieceKeyByProp(...args: any[]): void;

    function getPieceProperties(...args: any[]): void;

    function getPiecesInBoard(...args: any[]): void;

    function getSubBoardNumber(): void;

    function indexCodeToPos(...args: any[]): number;

    function injectPiece(...args: any[]): void;

    function isBlack(c: any): void;

    function isCharPiecesInBoard(...args: any[]): void;

    function isHaveCaptured(...args: any[]): void;

    function isPosInBoard(...args: any[]): void;

    function isStateCount(...args: any[]): void;

    function isValidPiece(piece: any): void;

    function isValidPiecesString(...args: any[]): void;

    function isValidPosXY(...args: any[]): void;

    function isWhite(c: any): void;

    function nerdPosToXY(...args: any[]): void;

    function nerdXyToPos(...args: any[]): number;

    function numToCode(...args: any[]): void;

    function numToCodeP(...args: any[]): void;

    function oppositeColor(...args: any[]): void;

    function p(x: any, y: any): void;

    function pointToIndexCode(...args: any[]): void;

    function posToIndexCode(...args: any[]): void;

    function rect(x: any, y: any, width: any, height: any): void;

    function replacePiecesString(...args: any[]): void;

    function res(width: any, height: any): void;

    function toBlackPiece(str: any): void;

    function toWhitePiece(str: any): void;

    function xyToIndexCode(...args: any[]): string;

}

export namespace renHelper {
    function toRen(...args: any[]): void;

}

